### ISSUE TITLE
Missing required fields: type for modules/tests/test_definitions.yaml

### ISSUE THREAD

**Issue by KalmanMeth** [SODALITE-EU/iac-platform-stack#10]
When running with the latest opera: 
`opera deploy -i input.yaml test1.yaml`
I get the following printed error message:
`modules/tests/test_definitions.yaml:40:38: [PropertyDefinition] Missing required fields: type`

where test1.yaml looks like this:
```
tosca_definitions_version: tosca_simple_yaml_1_3

imports:
  - modules/tests/test_definitions.yaml

topology_template:

  node_templates:

  # test the mechanism
    my_registration:
      type: sodalite.nodes.Tests.Text.Command
      properties:
        command: echo Hello
        comparable_string:  Hello

    my_registration2:
      type: sodalite.nodes.Tests.Text.Command
      properties:
        command: echo Hello
        comparable_string:  Bye

```
